spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

    defer-datasource-initialization: true

#  sql:
#    init:
#      mode: always

fcm:
  key:
    path: firebase-adminsdk.json
    scope: https://www.googleapis.com/auth/cloud-platform
  api:
    url: https://fcm.googleapis.com/v1/projects/fcm-practice/messages:send
  topic:
    "sopt-topic"